-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

COMMENT ON SCHEMA public IS 'standard public schema';

-- DROP TYPE public."change_request_model";

CREATE TYPE public."change_request_model" AS ENUM (
	'estandar',
	'normal',
	'emergencia');

-- DROP TYPE public."change_request_priority";

CREATE TYPE public."change_request_priority" AS ENUM (
	'baja',
	'media',
	'alta',
	'critica');

-- DROP TYPE public."change_request_status";

CREATE TYPE public."change_request_status" AS ENUM (
	'borrador',
	'pendiente_revision',
	'pendiente_cab',
	'aprobada',
	'en_progreso',
	'pendiente_pir',
	'cerrada',
	'completada',
	'rechazada',
	'cancelada');

-- DROP TYPE public."estado_inscripcion";

CREATE TYPE public."estado_inscripcion" AS ENUM (
	'pendiente_requisitos',
	'pendiente_pago',
	'pendiente_revision',
	'confirmada',
	'rechazada');

-- DROP TYPE public."estado_pago";

CREATE TYPE public."estado_pago" AS ENUM (
	'pendiente',
	'en_revision',
	'aprobado',
	'rechazado');

-- DROP TYPE public."estado_verificacion";

CREATE TYPE public."estado_verificacion" AS ENUM (
	'no_solicitado',
	'pendiente',
	'verificado');

-- DROP TYPE public."rol_usuario";

CREATE TYPE public."rol_usuario" AS ENUM (
	'administrador',
	'general');

-- DROP TYPE public."tipo_audiencia";

CREATE TYPE public."tipo_audiencia" AS ENUM (
	'publico_general',
	'estudiantes_uta',
	'estudiantes_facultad',
	'estudiantes_carrera');

-- DROP TYPE public."tipo_evento";

CREATE TYPE public."tipo_evento" AS ENUM (
	'curso',
	'conferencia',
	'congreso',
	'webinar',
	'socializacion',
	'otro');

-- DROP SEQUENCE public."Eventos_id_seq";

CREATE SEQUENCE public."Eventos_id_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.carreras_id_seq;

CREATE SEQUENCE public.carreras_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.cdc_roles_id_seq;

CREATE SEQUENCE public.cdc_roles_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.inscripcion_requisitos_presentados_id_seq;

CREATE SEQUENCE public.inscripcion_requisitos_presentados_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.inscripciones_id_seq;

CREATE SEQUENCE public.inscripciones_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.pagos_id_seq;

CREATE SEQUENCE public.pagos_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.requisitos_id_seq;

CREATE SEQUENCE public.requisitos_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.rfc_aprobaciones_id_seq;

CREATE SEQUENCE public.rfc_aprobaciones_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.rfc_pir_id_seq;

CREATE SEQUENCE public.rfc_pir_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.rfc_tareas_tecnicas_id_seq;

CREATE SEQUENCE public.rfc_tareas_tecnicas_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.solicitudes_de_cambio_id_seq;

CREATE SEQUENCE public.solicitudes_de_cambio_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- public.carreras definition

-- Drop table

-- DROP TABLE public.carreras;

CREATE TABLE public.carreras (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nombre text NOT NULL,
	facultad text DEFAULT 'FISEI'::text NOT NULL,
	CONSTRAINT carreras_nombre_key UNIQUE (nombre),
	CONSTRAINT carreras_pkey PRIMARY KEY (id)
);


-- public.cdc_roles definition

-- Drop table

-- DROP TABLE public.cdc_roles;

CREATE TABLE public.cdc_roles (
	id serial4 NOT NULL,
	nombre_rol text NOT NULL,
	descripcion text NULL,
	CONSTRAINT cdc_roles_nombre_rol_key UNIQUE (nombre_rol),
	CONSTRAINT cdc_roles_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE public.cdc_roles IS 'Define los roles que existen dentro del proceso de Gestión de Cambios.';


-- public.configuracion_sitio definition

-- Drop table

-- DROP TABLE public.configuracion_sitio;

CREATE TABLE public.configuracion_sitio (
	id int4 DEFAULT 1 NOT NULL,
	logo_url text NULL,
	banner_principal_url text NULL,
	contenido_estatico jsonb NULL,
	CONSTRAINT configuracion_sitio_pkey PRIMARY KEY (id),
	CONSTRAINT unique_row CHECK ((id = 1))
);


-- public."Eventos" definition

-- Drop table

-- DROP TABLE public."Eventos";

CREATE TABLE public."Eventos" (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	nombre text NOT NULL,
	responsable_id uuid NULL,
	estado text DEFAULT 'borrador'::text NOT NULL,
	descripcion text NULL,
	tipo public."tipo_evento" NULL,
	docente_id uuid NULL,
	fecha_inicio_evento timestamptz NULL,
	fecha_fin_evento timestamptz NULL,
	fecha_inicio_inscripcion timestamptz NULL,
	fecha_fin_inscripcion timestamptz NULL,
	es_pagado bool DEFAULT false NOT NULL,
	costo numeric(10, 2) DEFAULT 0 NULL,
	genera_certificado bool DEFAULT false NOT NULL,
	numero_horas int4 NULL,
	nota_aprobacion numeric(5, 2) DEFAULT 70.00 NULL,
	audiencia public."tipo_audiencia" DEFAULT 'publico_general'::tipo_audiencia NOT NULL,
	updated_at timestamptz DEFAULT now() NULL,
	imagen_url text NULL,
	CONSTRAINT "Eventos_pkey" PRIMARY KEY (id)
);


-- public.cdc_usuarios_roles definition

-- Drop table

-- DROP TABLE public.cdc_usuarios_roles;

CREATE TABLE public.cdc_usuarios_roles (
	usuario_id uuid NOT NULL,
	rol_id int4 NOT NULL,
	CONSTRAINT cdc_usuarios_roles_pkey PRIMARY KEY (usuario_id, rol_id)
);
COMMENT ON TABLE public.cdc_usuarios_roles IS 'Asigna roles del módulo de cambios a los usuarios del sistema.';


-- public.eventos_carreras definition

-- Drop table

-- DROP TABLE public.eventos_carreras;

CREATE TABLE public.eventos_carreras (
	evento_id int8 NOT NULL,
	carrera_id int8 NOT NULL,
	CONSTRAINT eventos_carreras_pkey PRIMARY KEY (evento_id, carrera_id)
);


-- public.inscripcion_requisitos_presentados definition

-- Drop table

-- DROP TABLE public.inscripcion_requisitos_presentados;

CREATE TABLE public.inscripcion_requisitos_presentados (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	inscripcion_id int8 NOT NULL,
	requisito_id int8 NOT NULL,
	archivo_url text NULL,
	estado text DEFAULT 'pendiente'::text NULL,
	CONSTRAINT inscripcion_requisitos_presentados_pkey PRIMARY KEY (id)
);


-- public.inscripciones definition

-- Drop table

-- DROP TABLE public.inscripciones;

CREATE TABLE public.inscripciones (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	usuario_id uuid NOT NULL,
	evento_id int8 NOT NULL,
	estado public."estado_inscripcion" DEFAULT 'pendiente_requisitos'::estado_inscripcion NOT NULL,
	fecha_inscripcion timestamptz DEFAULT now() NULL,
	nota_final numeric(5, 2) NULL,
	asistencia numeric(5, 2) NULL,
	certificado_url text NULL,
	CONSTRAINT inscripciones_pkey PRIMARY KEY (id),
	CONSTRAINT inscripciones_usuario_id_evento_id_key UNIQUE (usuario_id, evento_id)
);


-- public.pagos definition

-- Drop table

-- DROP TABLE public.pagos;

CREATE TABLE public.pagos (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	inscripcion_id int8 NOT NULL,
	comprobante_url text NULL,
	estado public."estado_pago" DEFAULT 'pendiente'::estado_pago NOT NULL,
	revisor_id uuid NULL,
	fecha_revision timestamptz NULL,
	fecha_carga_comprobante timestamptz NULL,
	motivo_rechazo text NULL,
	CONSTRAINT pagos_inscripcion_id_key UNIQUE (inscripcion_id),
	CONSTRAINT pagos_pkey PRIMARY KEY (id)
);


-- public.perfiles definition

-- Drop table

-- DROP TABLE public.perfiles;

CREATE TABLE public.perfiles (
	id uuid NOT NULL,
	nombre1 text NOT NULL,
	nombre2 text NULL,
	apellido1 text NOT NULL,
	apellido2 text NULL,
	cedula varchar(50) NOT NULL,
	telefono varchar(10) NOT NULL,
	email text NOT NULL,
	fecha_nacimiento date NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	is_active bool DEFAULT true NOT NULL,
	rol public."rol_usuario" DEFAULT 'general'::rol_usuario NOT NULL,
	deleted_at timestamptz NULL,
	comprobante_carrera_url text NULL,
	"estado_verificacion" public."estado_verificacion" DEFAULT 'no_solicitado'::estado_verificacion NOT NULL,
	CONSTRAINT perfiles_cedula_key UNIQUE (cedula),
	CONSTRAINT perfiles_email_key UNIQUE (email),
	CONSTRAINT perfiles_pkey PRIMARY KEY (id),
	CONSTRAINT telefono_length CHECK ((char_length((telefono)::text) = 10))
);
CREATE INDEX idx_perfiles_deleted_at ON public.perfiles USING btree (deleted_at);
COMMENT ON TABLE public.perfiles IS 'Tabla para almacenar los perfiles de los usuarios generales.';

-- Table Triggers

create trigger tg_perfiles_updated_at before
update
    on
    public.perfiles for each row execute function set_updated_at();


-- public.perfiles_carreras definition

-- Drop table

-- DROP TABLE public.perfiles_carreras;

CREATE TABLE public.perfiles_carreras (
	usuario_id uuid NOT NULL,
	carrera_id int8 NOT NULL,
	CONSTRAINT perfiles_carreras_pkey PRIMARY KEY (usuario_id, carrera_id)
);


-- public.requisitos definition

-- Drop table

-- DROP TABLE public.requisitos;

CREATE TABLE public.requisitos (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	evento_id int8 NOT NULL,
	descripcion text NOT NULL,
	tipo_requisito text DEFAULT 'documento'::text NULL,
	CONSTRAINT requisitos_pkey PRIMARY KEY (id)
);


-- public.rfc_aprobaciones definition

-- Drop table

-- DROP TABLE public.rfc_aprobaciones;

CREATE TABLE public.rfc_aprobaciones (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	solicitud_id int8 NOT NULL,
	aprobador_id uuid NOT NULL,
	decision bool NOT NULL,
	comentarios text NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT rfc_aprobaciones_pkey PRIMARY KEY (id),
	CONSTRAINT rfc_aprobaciones_solicitud_id_aprobador_id_key UNIQUE (solicitud_id, aprobador_id)
);
COMMENT ON TABLE public.rfc_aprobaciones IS 'Registra el voto (aprobación/rechazo) de cada miembro del CAB.';


-- public.rfc_cab_miembros definition

-- Drop table

-- DROP TABLE public.rfc_cab_miembros;

CREATE TABLE public.rfc_cab_miembros (
	solicitud_id int8 NOT NULL,
	miembro_id uuid NOT NULL,
	CONSTRAINT rfc_cab_miembros_pkey PRIMARY KEY (solicitud_id, miembro_id)
);
COMMENT ON TABLE public.rfc_cab_miembros IS 'Asigna los miembros del Comité Asesor de Cambios (CAB) a una solicitud específica.';


-- public.rfc_desarrolladores_asignados definition

-- Drop table

-- DROP TABLE public.rfc_desarrolladores_asignados;

CREATE TABLE public.rfc_desarrolladores_asignados (
	solicitud_id int8 NOT NULL,
	desarrollador_id uuid NOT NULL,
	CONSTRAINT rfc_desarrolladores_asignados_pkey PRIMARY KEY (solicitud_id, desarrollador_id)
);
COMMENT ON TABLE public.rfc_desarrolladores_asignados IS 'Asigna los líderes técnicos o desarrolladores responsable de implementar un cambio.';


-- public.rfc_pir definition

-- Drop table

-- DROP TABLE public.rfc_pir;

CREATE TABLE public.rfc_pir (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	solicitud_id int8 NOT NULL,
	revisor_id uuid NOT NULL,
	exitoso bool NOT NULL,
	notas text NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT rfc_pir_pkey PRIMARY KEY (id),
	CONSTRAINT rfc_pir_solicitud_id_key UNIQUE (solicitud_id)
);
CREATE INDEX idx_rfc_pir_solicitud_id ON public.rfc_pir USING btree (solicitud_id);


-- public.rfc_tareas_tecnicas definition

-- Drop table

-- DROP TABLE public.rfc_tareas_tecnicas;

CREATE TABLE public.rfc_tareas_tecnicas (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	solicitud_id int8 NOT NULL,
	descripcion text NOT NULL,
	asignado_id uuid NULL,
	completada bool DEFAULT false NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT rfc_tareas_tecnicas_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE public.rfc_tareas_tecnicas IS 'Tareas técnicas a ejecutar para implementar un cambio aprobado.';


-- public.solicitudes_de_cambio definition

-- Drop table

-- DROP TABLE public.solicitudes_de_cambio;

CREATE TABLE public.solicitudes_de_cambio (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	titulo text NOT NULL,
	descripcion text NULL,
	justificacion text NULL,
	impacto_potencial text NULL,
	solicitante_id uuid NULL,
	gestor_id uuid NULL,
	estado public."change_request_status" DEFAULT 'borrador'::change_request_status NOT NULL,
	prioridad public."change_request_priority" DEFAULT 'media'::change_request_priority NOT NULL,
	github_issue_url text NULL,
	github_issue_number int4 NULL,
	github_pr_url text NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	modelo public."change_request_model" DEFAULT 'normal'::change_request_model NOT NULL,
	CONSTRAINT solicitudes_de_cambio_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE public.solicitudes_de_cambio IS 'Tabla central para las "Requests for Change" (RFC).';


-- public."Eventos" foreign keys

ALTER TABLE public."Eventos" ADD CONSTRAINT "Eventos_docente_id_fkey" FOREIGN KEY (docente_id) REFERENCES public.perfiles(id);
ALTER TABLE public."Eventos" ADD CONSTRAINT eventos_responsable_id_fkey_correcta FOREIGN KEY (responsable_id) REFERENCES public.perfiles(id);


-- public.cdc_usuarios_roles foreign keys

ALTER TABLE public.cdc_usuarios_roles ADD CONSTRAINT cdc_usuarios_roles_rol_id_fkey FOREIGN KEY (rol_id) REFERENCES public.cdc_roles(id) ON DELETE CASCADE;
ALTER TABLE public.cdc_usuarios_roles ADD CONSTRAINT cdc_usuarios_roles_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.perfiles(id) ON DELETE CASCADE;


-- public.eventos_carreras foreign keys

ALTER TABLE public.eventos_carreras ADD CONSTRAINT eventos_carreras_carrera_id_fkey FOREIGN KEY (carrera_id) REFERENCES public.carreras(id) ON DELETE CASCADE;
ALTER TABLE public.eventos_carreras ADD CONSTRAINT eventos_carreras_evento_id_fkey FOREIGN KEY (evento_id) REFERENCES public."Eventos"(id) ON DELETE CASCADE;


-- public.inscripcion_requisitos_presentados foreign keys

ALTER TABLE public.inscripcion_requisitos_presentados ADD CONSTRAINT inscripcion_requisitos_presentados_inscripcion_id_fkey FOREIGN KEY (inscripcion_id) REFERENCES public.inscripciones(id) ON DELETE CASCADE;
ALTER TABLE public.inscripcion_requisitos_presentados ADD CONSTRAINT inscripcion_requisitos_presentados_requisito_id_fkey FOREIGN KEY (requisito_id) REFERENCES public.requisitos(id) ON DELETE CASCADE;


-- public.inscripciones foreign keys

ALTER TABLE public.inscripciones ADD CONSTRAINT inscripciones_evento_id_fkey FOREIGN KEY (evento_id) REFERENCES public."Eventos"(id) ON DELETE CASCADE;
ALTER TABLE public.inscripciones ADD CONSTRAINT inscripciones_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.perfiles(id);


-- public.pagos foreign keys

ALTER TABLE public.pagos ADD CONSTRAINT pagos_inscripcion_id_fkey FOREIGN KEY (inscripcion_id) REFERENCES public.inscripciones(id) ON DELETE CASCADE;
ALTER TABLE public.pagos ADD CONSTRAINT pagos_revisor_id_fkey FOREIGN KEY (revisor_id) REFERENCES public.perfiles(id);


-- public.perfiles foreign keys

ALTER TABLE public.perfiles ADD CONSTRAINT perfiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;


-- public.perfiles_carreras foreign keys

ALTER TABLE public.perfiles_carreras ADD CONSTRAINT perfiles_carreras_carrera_id_fkey FOREIGN KEY (carrera_id) REFERENCES public.carreras(id) ON DELETE CASCADE;
ALTER TABLE public.perfiles_carreras ADD CONSTRAINT perfiles_carreras_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.perfiles(id) ON DELETE CASCADE;


-- public.requisitos foreign keys

ALTER TABLE public.requisitos ADD CONSTRAINT requisitos_evento_id_fkey FOREIGN KEY (evento_id) REFERENCES public."Eventos"(id) ON DELETE CASCADE;


-- public.rfc_aprobaciones foreign keys

ALTER TABLE public.rfc_aprobaciones ADD CONSTRAINT rfc_aprobaciones_aprobador_id_fkey FOREIGN KEY (aprobador_id) REFERENCES public.perfiles(id);
ALTER TABLE public.rfc_aprobaciones ADD CONSTRAINT rfc_aprobaciones_solicitud_id_fkey FOREIGN KEY (solicitud_id) REFERENCES public.solicitudes_de_cambio(id) ON DELETE CASCADE;


-- public.rfc_cab_miembros foreign keys

ALTER TABLE public.rfc_cab_miembros ADD CONSTRAINT rfc_cab_miembros_miembro_id_fkey FOREIGN KEY (miembro_id) REFERENCES public.perfiles(id);
ALTER TABLE public.rfc_cab_miembros ADD CONSTRAINT rfc_cab_miembros_solicitud_id_fkey FOREIGN KEY (solicitud_id) REFERENCES public.solicitudes_de_cambio(id) ON DELETE CASCADE;


-- public.rfc_desarrolladores_asignados foreign keys

ALTER TABLE public.rfc_desarrolladores_asignados ADD CONSTRAINT rfc_desarrolladores_asignados_desarrollador_id_fkey FOREIGN KEY (desarrollador_id) REFERENCES public.perfiles(id) ON DELETE CASCADE;
ALTER TABLE public.rfc_desarrolladores_asignados ADD CONSTRAINT rfc_desarrolladores_asignados_solicitud_id_fkey FOREIGN KEY (solicitud_id) REFERENCES public.solicitudes_de_cambio(id) ON DELETE CASCADE;


-- public.rfc_pir foreign keys

ALTER TABLE public.rfc_pir ADD CONSTRAINT fk_revisor FOREIGN KEY (revisor_id) REFERENCES public.perfiles(id);
ALTER TABLE public.rfc_pir ADD CONSTRAINT fk_solicitud FOREIGN KEY (solicitud_id) REFERENCES public.solicitudes_de_cambio(id) ON DELETE CASCADE;


-- public.rfc_tareas_tecnicas foreign keys

ALTER TABLE public.rfc_tareas_tecnicas ADD CONSTRAINT rfc_tareas_tecnicas_asignado_id_fkey FOREIGN KEY (asignado_id) REFERENCES public.perfiles(id);
ALTER TABLE public.rfc_tareas_tecnicas ADD CONSTRAINT rfc_tareas_tecnicas_solicitud_id_fkey FOREIGN KEY (solicitud_id) REFERENCES public.solicitudes_de_cambio(id) ON DELETE CASCADE;


-- public.solicitudes_de_cambio foreign keys

ALTER TABLE public.solicitudes_de_cambio ADD CONSTRAINT solicitudes_de_cambio_gestor_id_fkey FOREIGN KEY (gestor_id) REFERENCES public.perfiles(id);
ALTER TABLE public.solicitudes_de_cambio ADD CONSTRAINT solicitudes_de_cambio_solicitante_id_fkey FOREIGN KEY (solicitante_id) REFERENCES public.perfiles(id);


-- public.eventos_con_responsable source

CREATE OR REPLACE VIEW public.eventos_con_responsable
AS SELECT e.id,
    e.nombre,
    e.estado,
    e.responsable_id,
    json_build_object('cedula', p.cedula, 'nombre1', p.nombre1, 'apellido1', p.apellido1) AS responsable_info
   FROM "Eventos" e
     LEFT JOIN perfiles p ON e.responsable_id = p.id;


-- public.vw_inscripciones_detalle source

CREATE OR REPLACE VIEW public.vw_inscripciones_detalle
AS SELECT i.id AS inscripcion_id,
    i.evento_id,
    (per.nombre1 || ' '::text) || per.apellido1 AS alumno,
    i.fecha_inscripcion,
    i.estado::text AS estado_inscripcion,
    COALESCE(p.estado::text, 'no aplica'::text) AS estado_pago,
    e.costo AS monto_esperado
   FROM inscripciones i
     JOIN perfiles per ON i.usuario_id = per.id
     JOIN "Eventos" e ON i.evento_id = e.id
     LEFT JOIN pagos p ON i.id = p.inscripcion_id
  ORDER BY i.fecha_inscripcion DESC;


-- public.vw_resumen_evento source

CREATE OR REPLACE VIEW public.vw_resumen_evento
AS SELECT e.id AS evento_id,
    e.nombre AS evento_nombre,
    e.estado AS estado_evento,
    count(i.id) AS total_inscripciones,
    count(i.id) FILTER (WHERE i.estado::text = 'aprobada'::text) AS inscripciones_aprobadas,
    count(i.id) FILTER (WHERE i.estado::text = ANY (ARRAY['pendiente_requisitos'::text, 'pendiente_pago'::text])) AS inscripciones_pendientes,
    count(i.id) FILTER (WHERE i.estado::text = 'rechazada'::text) AS inscripciones_rechazadas,
    COALESCE(sum(e.costo) FILTER (WHERE p.estado::text = 'confirmado'::text), 0::numeric) AS monto_confirmado,
    COALESCE(sum(e.costo) FILTER (WHERE p.estado::text = ANY (ARRAY['pendiente'::text, 'fallido'::text])), 0::numeric) AS monto_pendiente
   FROM "Eventos" e
     LEFT JOIN inscripciones i ON e.id = i.evento_id
     LEFT JOIN pagos p ON i.id = p.inscripcion_id
  GROUP BY e.id;



-- DROP FUNCTION public.approve_payment(int8, uuid);

CREATE OR REPLACE FUNCTION public.approve_payment(p_inscripcion_id bigint, p_revisor_id uuid)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- 1. Actualizar el estado del pago a 'aprobado'
    UPDATE public.pagos
    SET 
        estado = 'aprobado',
        fecha_revision = now(),
        revisor_id = p_revisor_id
    WHERE inscripcion_id = p_inscripcion_id;

    -- 2. Actualizar el estado de la inscripción a 'confirmada'
    UPDATE public.inscripciones
    SET estado = 'confirmada'
    WHERE id = p_inscripcion_id;
END;
$function$
;

-- DROP FUNCTION public.assign_event_careers(int8, _int4);

CREATE OR REPLACE FUNCTION public.assign_event_careers(p_event_id bigint, p_career_ids integer[])
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  -- Primero, borra las asociaciones de carrera existentes para el evento.
  DELETE FROM public.eventos_carreras WHERE evento_id = p_event_id;

  -- Luego, si se proporcionó una lista de carreras, inserta las nuevas.
  IF array_length(p_career_ids, 1) > 0 THEN
    INSERT INTO public.eventos_carreras (evento_id, carrera_id)
    SELECT p_event_id, unnest(p_career_ids);
  END IF;
END;
$function$
;

-- DROP FUNCTION public.assign_user_careers(uuid, _int4);

CREATE OR REPLACE FUNCTION public.assign_user_careers(p_user_id uuid, p_career_ids integer[])
 RETURNS void
 LANGUAGE plpgsql
AS $function$
     BEGIN
       -- Primero, borra las asociaciones de carrera existentes par el usuario.
       DELETE FROM public.perfiles_carreras WHERE usuario_id = p_user_id;
    
       -- Luego, inserta las nuevas.
       -- Si el array no está vacío, se ejecuta la inserción.
       IF array_length(p_career_ids, 1) > 0 THEN
        INSERT INTO public.perfiles_carreras (usuario_id,carrera_id)
        SELECT p_user_id, unnest(p_career_ids);
      END IF;
    END;
    $function$
;

-- DROP FUNCTION public.assign_user_cdc_roles(uuid, _int4);

CREATE OR REPLACE FUNCTION public.assign_user_cdc_roles(p_user_id uuid, p_role_ids integer[])
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- Primero, eliminar todos los roles del Módulo de Cambios (CDC) existentes para este usuario.
    -- Esto simplifica la lógica, ya que no tenemos que comparar qué roles se añadieron o eliminaron.
    DELETE FROM public.cdc_usuarios_roles
    WHERE usuario_id = p_user_id;

    -- Luego, si la lista de roles no está vacía,
    -- insertamos los nuevos roles desde el array proporcionado.
    -- La función unnest() expande un array en un conjunto de filas,
    -- permitiendo una inserción masiva.
    IF array_length(p_role_ids, 1) > 0 THEN
        INSERT INTO public.cdc_usuarios_roles (usuario_id, rol_id)
        SELECT p_user_id, role_id
        FROM unnest(p_role_ids) AS role_id;
    END IF;
END;
$function$
;

-- DROP FUNCTION public.enroll_paid_event(uuid, int8, text);

CREATE OR REPLACE FUNCTION public.enroll_paid_event(p_user_id uuid, p_event_id bigint, p_comprobante_url text)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
DECLARE
  new_inscripcion_id int;
BEGIN
  -- 1. Verificar si ya existe una inscripción activa (no rechazada) para evitar duplicados.
  IF EXISTS (
    SELECT 1 FROM public.inscripciones
    WHERE usuario_id = p_user_id
      AND evento_id = p_event_id
      AND estado <> 'rechazada'
  ) THEN
    RAISE EXCEPTION 'Ya existe una inscripción activa o pendiente para este evento.';
  END IF;

  -- 2. Crear el registro de inscripción con el estado 'pendiente_pago'.
  INSERT INTO public.inscripciones (usuario_id, evento_id, estado)
  VALUES (p_user_id, p_event_id, 'pendiente_pago')
  RETURNING id INTO new_inscripcion_id;

  -- 3. Crear el registro de pago asociado, con el estado 'en_revision'.
  INSERT INTO public.pagos (inscripcion_id, comprobante_url, estado, fecha_carga_comprobante)
  VALUES (new_inscripcion_id, p_comprobante_url, 'en_revision', now());

  -- 4. Devolver el ID de la nueva inscripción.
  RETURN new_inscripcion_id;
END;
$function$
;

-- DROP FUNCTION public.get_dashboard_stats();

CREATE OR REPLACE FUNCTION public.get_dashboard_stats()
 RETURNS json
 LANGUAGE plpgsql
AS $function$
DECLARE
    admin_count integer;
    general_user_count integer;
    event_count integer;
    responsable_count integer;
BEGIN
    -- Contar administradores
    SELECT count(*)
    INTO admin_count
    FROM public.perfiles
    WHERE rol = 'administrador';

    -- Contar usuarios generales
    SELECT count(*)
    INTO general_user_count
    FROM public.perfiles
    WHERE rol = 'general';

    -- Contar eventos totales
    SELECT count(*)
    INTO event_count
    FROM public."Eventos";

    -- Contar responsables únicos de eventos
    SELECT count(DISTINCT responsable_id)
    INTO responsable_count
    FROM public."Eventos"
    WHERE responsable_id IS NOT NULL;

    -- Devolver todos los conteos en un solo objeto JSON
    RETURN json_build_object(
        'admins', admin_count,
        'general_users', general_user_count,
        'events', event_count,
        'responsables', responsable_count
    );
END;
$function$
;

-- DROP FUNCTION public.get_users_by_cdc_role(text);

CREATE OR REPLACE FUNCTION public.get_users_by_cdc_role(role_name text)
 RETURNS TABLE(id uuid, nombre1 text, apellido1 text)
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY
    SELECT
        p.id,
        p.nombre1,
        p.apellido1
    FROM
        public.perfiles p
    JOIN
        public.cdc_usuarios_roles cur ON p.id = cur.usuario_id
    JOIN
        public.cdc_roles cr ON cur.rol_id = cr.id
    WHERE
        cr.nombre_rol = role_name;
END;
$function$
;

-- DROP FUNCTION public.get_visible_event_ids_for_user(uuid);

CREATE OR REPLACE FUNCTION public.get_visible_event_ids_for_user(p_user_id uuid)
 RETURNS TABLE(id bigint)
 LANGUAGE plpgsql
AS $function$
DECLARE
  is_verified boolean;
BEGIN
  -- Check if the user is verified
  SELECT p.estado_verificacion = 'verificado'
  INTO is_verified
  FROM public.perfiles p
  WHERE p.id = p_user_id;

  -- Return event IDs based on visibility rules
  RETURN QUERY
  SELECT e.id
  FROM public."Eventos" e
  WHERE
    e.estado = 'publicado' AND (
      -- Rule 1: Event is for the general public, always visible
      e.audiencia = 'publico_general'
      OR
      -- Rule 2: Event is for any UTA student (assuming a verified user is one)
      e.audiencia = 'estudiantes_uta' AND is_verified
      OR
      -- Rule 3: Event is for any student of the faculty (assuming FISEI)
      e.audiencia = 'estudiantes_facultad' AND is_verified
      OR
      -- Rule 4: Event is for a specific career and the user belongs to it
      (
        e.audiencia = 'estudiantes_carrera' AND
        is_verified AND
        EXISTS (
          SELECT 1
          FROM public.eventos_carreras ec
          JOIN public.perfiles_carreras pc ON ec.carrera_id = pc.carrera_id
          WHERE ec.evento_id = e.id
            AND pc.usuario_id = p_user_id
        )
      )
    );
END;
$function$
;

-- DROP FUNCTION public.handle_new_user_with_metadata();

CREATE OR REPLACE FUNCTION public.handle_new_user_with_metadata()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  -- Verificar si ya existe un perfil con el mismo id
  IF NOT EXISTS (SELECT 1 FROM public.perfiles WHERE id = new.id) THEN
    INSERT INTO public.perfiles (
      id,
      email,
      rol,
      nombre1,
      nombre2,
      apellido1,
      apellido2,
      cedula,
      telefono,
      fecha_nacimiento,
      comprobante_carrera_url,
      estado_verificacion
    )
    VALUES (
      new.id,
      new.email,
      (new.raw_user_meta_data->>'rol_usuario')::public.rol_usuario,
      new.raw_user_meta_data->>'nombre1',
      new.raw_user_meta_data->>'nombre2',
      new.raw_user_meta_data->>'apellido1',
      newraw_user_meta_data->>'apellido2',
      new.raw_user_meta_data->>'cedula',
      new.raw_user_meta_data->>'telefono',
      CASE 
        WHEN new.raw_user_meta_data->>'fecha_nacimiento' = '' OR new.raw_user_meta_data->>'fecha_nacimiento' IS NULL THEN NULL
        ELSE (new.raw_user_meta_data->>'fecha_nacimiento')::date
      END,
      new.raw_user_meta_data->>'comprobante_carrera_url',
      CASE
        WHEN new.raw_user_meta_data->>'comprobante_carrera_url' IS NOT NULL THEN 'pendiente'::public.estado_verificacion
        ELSE 'no_solicitado'::public.estado_verificacion
      END
    );
  END IF;
  RETURN new;
END;
$function$
;

-- DROP FUNCTION public.reject_payment(int8, uuid, text);

CREATE OR REPLACE FUNCTION public.reject_payment(p_inscripcion_id bigint, p_revisor_id uuid, p_motivo_rechazo text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- 1. Actualizar el estado del pago a 'rechazado' y guardar el motivo.
    UPDATE public.pagos
    SET 
        estado = 'rechazado',
        fecha_revision = now(),
        revisor_id = p_revisor_id,
        motivo_rechazo = p_motivo_rechazo
    WHERE inscripcion_id = p_inscripcion_id;

    -- 2. Devolver el estado de la inscripción a 'pendiente_pago' para que el usuario pueda reintentar.
    UPDATE public.inscripciones
    SET estado = 'pendiente_pago'
    WHERE id = p_inscripcion_id;
END;
$function$
;

-- DROP FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end; $function$
;